### ISSUE TITLE
Over-the-air self updates

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#43]
Trigger firmware updates when we receive an MQTT message that asks the board to upgrade its version.

Here is an example of the message I'm going to send:
```json
"state" {
  "desired" : {
    "coolboard" : {
      "firmwareUpdate" : {
        "fingerPrint" : "FA CD 6E 04 A0 2F E8 9A 92 00 37 4A EE 51 C2 D2
D9 99 55 AA",
        "url" : "https://my-update-server/firmware.bin",
        "version" : "v0.1.5"
      }
    }
  }
}
```

then, you should use the [HTTPUpdate library](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266httpUpdate) provided in SDK 2.4.1 - see `examples`. 

**The URL should be HTTPS, so make sure to get the [SHA1 fingerprint](https://en.wikipedia.org/wiki/Public_key_fingerprint) of the server's certificate**

**Comment by 3rwww1** [comment]
@trap98 @Kameeno I want you both to collaborate on this and make a clean pull request by the end of the week. @Kameeno please bring @trap98 up-to-speed on the way the current firmware/API works and ask for my help... When you **really** need it :)

**Comment by Kameeno** [comment]
it's going good for the classic HTTP update, so now..
i'm looking for https updates, i found this on the ESP8266HTTPUpdate.cpp

> HTTPUpdateResult ESP8266HTTPUpdate::update(const String& host, uint16_t port, const String& uri, const String& currentVersion,
>         bool https, const String& httpsFingerprint, bool reboot)
> {
> 

the reference say this : 


> **t_httpUpdate_return ESP8266HTTPUpdate::update** (
>   |   | String | host,
>   |   | uint16_t | port,
>   |   | String | url = "/",
>   |   | String | current_version = "",
>   |   | bool | https = false,
>   |   | String | httpsFingerprint = "",
>   |   | bool | reboot = true
>   | )

the document of reference is here : 
[https://links2004.github.io/Arduino/df/d31/class_e_s_p8266_h_t_t_p_update.html](url)
i propose to have host reference (where you want) and to send the address of the binary file,
for the rest... **i found a LOOP of update, the cause is from the mqtt ( or not?)
so, when i send my json message, the coolboard she getting on update and she reboot with new firmware.. and she re-check on the mqtt but... she found again the last message about OTA.** 

one more thing

the function on the original library she do this:

> HTTPUpdateResult ESP8266HTTPUpdate::handleUpdate(HTTPClient& http, const String& currentVersion, bool spiffs)
> {
> 
>     HTTPUpdateResult ret = HTTP_UPDATE_FAILED;
> 
>     // use HTTP/1.0 for update since the update handler not support any transfer Encoding
>     http.useHTTP10(true);
>     http.setTimeout(8000);
>     http.setUserAgent(F("ESP8266-http-Update"));
>     http.addHeader(F("x-ESP8266-STA-MAC"), WiFi.macAddress());
>     http.addHeader(F("x-ESP8266-AP-MAC"), WiFi.softAPmacAddress());
>     http.addHeader(F("x-ESP8266-free-space"), String(ESP.getFreeSketchSpace()));
>     http.addHeader(F("x-ESP8266-sketch-size"), String(ESP.getSketchSize()));
>     http.addHeader(F("x-ESP8266-sketch-md5"), String(ESP.getSketchMD5()));
>     http.addHeader(F("x-ESP8266-chip-size"), String(ESP.getFlashChipRealSize()));
>     http.addHeader(F("x-ESP8266-sdk-version"), ESP.getSdkVersion());

are the http header the cause of the block to make a http/https REQUEST to GITHUB?
and i'm little bit confused about "currentVersion" if is meaning "HTTP/1.0" version or..... just the current version to send a HTTP Post of the firmware running now ?

**Comment by Kameeno** [comment]
on the new porting on the last SDK, cause bug about connectivity, so, if on your spiffs you got some saved SSID/PASSWORD on wificonfig.json the board, i think she did not take the credential and arent compared with the current wifi arround.

ok, if you flash your firmware and on your spiffs, wificonfig.json did not contain some wifi credentials, you arrive to connect, i do my OTA update, (with the same firmware) on reboot she didn't getting credentials from wificonfig.json

actually i missed my coolboard to make a good bugfix about
